# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Luna Vanaman"
description: "Motion | Storytelling | Visual Data Communication"
author:      "Luna Vanaman"

icon:
  img: "lv.png"
  alt: "LV"
